[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "charity-tasker.netlify.app"
  to = "https://charity-tasker.herokuapp.com/:splat"
  status = 200
  force = true
